---
name: Publish to Python Package Index (PyPI) Without TestPyPI.
on:
  workflow_dispatch:
jobs:
  pypi-notest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Ensure that Python is Installed.
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Ensure that the Package Builds.
        run: |
          python3 -m pip install build twine
          python3 -m build
          python3 -m twine check dist/*
      - name: Publish to PyPI.
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
